-- Add version column for optimistic locking to all editable tables.

ALTER TABLE facilitators ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE courses ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sessions ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE session_facilitators ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE attendance ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE session_feedback ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE import_jobs ADD COLUMN version INTEGER NOT NULL DEFAULT 1;